on:
  push:
    branches:
      - "dev" # 只针对 dev 分支
    paths:
      - ".github/workflows/*"
      # - '__test__/**' # dev 不需要立即测试
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "bin/*"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa # secret 在这里配置 https://github.com/imooc-lego/biz-editor-server/settings/secrets #给4私要给测试机
          chmod 600 ~/.ssh/id_rsa

      - name: deploy # 部署
        run: |
          ssh work@182.92.168.192"
            # 然后 git clone https://github.com/bangbang6/biz-editor-server.git -b dev （私有仓库，使用 github 用户名和密码）
            # 记得删除 origin ，否则会暴露 github 密码
            cd /home/work/immoc-lego/biz-editor-server;
            git remote add origin https://github.com/bangbang6/biz-editor-server.git;
            git checkout dev;
            git pull origin dev; # 重新下载最新代码
            git remote remove origin; # 删除 origin ，否则会暴露 github 密码
            # 启动 docker
            docker-compose build editor-server; # 和 docker-compose.yml service 名字一致
            docker-compose up -d;
          "
      - name: delete ssh key # 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
